### ISSUE TITLE
Scan doesn't work on fresh project and install

### ISSUE THREAD

**Issue by slakbal** [themsaid/laravel-langman-gui#27] opened 2017-05-24 12:24 UTC
Hi Mohammed,

I have a fresh install of everything and a single view with the following:

__("This is a test")

Clicking on the scan I can see that the endpoint does return the correct value:

["This is a test"]

but the Vue component throws the following error:

`
langman.js:42763 Uncaught TypeError: Cannot read property 'This is a test' of undefined
    at Vue$3.addNewKey (langman.js:42763)
    at Vue$3.boundFn [as addNewKey] (langman.js:33189)
    at _.forEach.key (langman.js:42835)
    at arrayEach (langman.js:14459)
    at Function.forEach (langman.js:23281)
    at Object.$.post.done.response (langman.js:42834)
    at fire (langman.js:6979)
    at Object.fireWith [as resolveWith] (langman.js:7109)
    at done (langman.js:12934)
    at XMLHttpRequest.<anonymous> (langman.js:13176)
`

Are you getting it also on a fresh install?

**Comment by stefro** [comment] 2017-05-27 06:58
I have this same issue.

**Comment by seschi98** [comment] 2017-06-01 16:48
Me too.

**Comment by robsontenorio** [comment] 2017-06-01 16:51
I think the problem is "cache files" from langman. Just delete all files in "storage/langmanGUI"

**Comment by seschi98** [comment] 2017-06-01 16:58
Did that already, problem still present...
When I click on "Scan" it just creates a new folder with an en.json in it. The file contains only an empty JSON Object.

**Comment by robsontenorio** [comment] 2017-06-01 18:21
1) clear cached files (storage/langmanGUI)
2) clear json files (en.json , fr.json ...)
3) open web interface with an  anonymous session in Chrome 
4) add a language file (ex "fr")
5) scan

**Comment by seschi98** [comment] 2017-06-01 18:28
Still not working 😏

**Comment by tutNichts** [comment] 2017-06-16 22:03
@themsaid some news here? I really want to use it! Would be great if it works! :-)

**Comment by bivinvinod** [comment] 2017-07-07 05:34
Same here...

**Comment by coldKingdom** [comment] 2017-08-01 18:35
I renamed the "en" folder in resources/lang to something else, cleared all the caches and started over again , seemed to be working for me :)

**Comment by themsaid** [comment] 2017-08-16 15:57
This is fixed now. thanks everyone.

**Closed as completed by themsaid** 2017-08-16 15:57 UTC

**Comment by ali-syria** [comment] 2017-09-24 19:52
still not working

**Comment by stefro** [comment] 2017-11-22 08:52
I had the same issue. I noticed that there was no json file for the base language in the `resources/lang` dir. 
After creating an `en.json` file with only `{}` in the file everything worked as expected.
